apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-prometheus
  namespace: techchallenge
  labels:
    app: techchallenge
    component: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techchallenge
      component: prometheus
  template:
    metadata:
      labels:
        app: techchallenge
        component: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-data
          emptyDir: {}