apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: techchallenge
  labels:
    app: techchallenge
    component: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 30s    
    scrape_configs: 
      - job_name: 'api'    
        scrape_interval: 5s   
        static_configs:
          - targets: ['svc-api:8080']
      - job_name: 'consumer'    
        scrape_interval: 5s   
        static_configs:
          - targets: ['svc-consumer:1234']
      - job_name: 'prometheus'        
        static_configs:
          - targets: ['localhost:9090']