apiVersion: v1
kind: Service
metadata:
  name: svc-prometheus
  namespace: techchallenge
  labels:
    app: techchallenge
    component: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30086
  selector:
    app: techchallenge
    component: prometheus
