apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-storage
  namespace: techchallenge
  labels:
    app: techchallenge
    component: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

