apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-database
  namespace: techchallenge
  labels:
    app: techchallenge
    component: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techchallenge
      component: db
  template:
    metadata:
      labels:
        app: techchallenge
        component: db
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456Tech"
            - name: MYSQL_DATABASE
              value: "techchallenge"
            - name: MYSQL_USER
              value: "sis_techchallenge"
            - name: MYSQL_PASSWORD
              value: "123456Tech"
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-storage