apiVersion: v1
kind: Service
metadata:
  name: svc-database
  namespace: techchallenge
  labels:
    app: techchallenge
    component: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30087
  selector:
    app: techchallenge
    component: db
  type: NodePort
