apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-bus
  namespace: techchallenge
  labels:
    app: techchallenge
    component: bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techchallenge
      component: bus
  template:
    metadata:
      labels:
        app: techchallenge
        component: bus
    spec:
      containers:
        - name: rabbitmq
          image: masstransit/rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672