apiVersion: v1
kind: Service
metadata:
  name: svc-bus
  namespace: techchallenge
  labels:
    app: techchallenge
    component: bus
spec:
  type: NodePort
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30083
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 30084
  selector:
    app: techchallenge
    component: bus
