apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-frontend
  namespace: techchallenge
  labels:
    app: techchallenge
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techchallenge
      component: frontend
  template:
    metadata:
      labels:
        app: techchallenge
        component: frontend
    spec:
      containers:
        - name: frontend
          image: jcoaio/techchallenge-frontend:latest
          imagePullPolicy: Always
          ports:
              - containerPort: 3000
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "100m"