apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
  namespace: techchallenge
  labels:
    app: techchallenge
    component: front
spec:
  selector:
    app: techchallenge
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30088
  type: NodePort
