apiVersion: v1
kind: Service
metadata:
  name: svc-grafana
  namespace: techchallenge
  labels:
    app: techchallenge
    component: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  selector:
    app: techchallenge
    component: grafana
